package dev.vibe.game.meme;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Random;

/** Complete legal-move chess board, including castling, promotion and en passant. */
public final class ChessGameState implements MemeGameState {
    private final char[][] board = new char[8][8];
    private int turn;
    private boolean whiteKingSide, whiteQueenSide, blackKingSide, blackQueenSide;
    private int enPassantColumn;
    private String status;
    private Move lastMove;

    public ChessGameState() { reset(); }

    @Override public void reset() {
        String[] setup = { "rnbqkbnr", "pppppppp", "        ", "        ", "        ", "        ", "PPPPPPPP", "RNBQKBNR" };
        for (int row = 0; row < 8; row++) for (int col = 0; col < 8; col++) board[row][col] = setup[row].charAt(col);
        turn = 0; whiteKingSide = whiteQueenSide = blackKingSide = blackQueenSide = true;
        enPassantColumn = -1; status = "White to move"; lastMove = null;
    }

    @Override public int getTurn() { return turn; }
    @Override public boolean isFinished() { return status.startsWith("Checkmate") || "Draw".equals(status) || status.startsWith("Stalemate"); }
    @Override public String getStatus() { return status; }
    public char get(int row, int column) { return board[row][column]; }
    public Move getLastMove() { return lastMove; }

    @Override public List<String> legalMoves() {
        List<String> result = new ArrayList<String>();
        for (Move move : legalMoveObjects()) result.add(san(move));
        return result;
    }

    public List<Move> legalMoveObjects() { return legalMoveObjects(turn); }
    private List<Move> legalMoveObjects(int side) {
        List<Move> pseudo = pseudoMoves(side);
        List<Move> result = new ArrayList<Move>();
        for (Move move : pseudo) {
            ChessGameState copy = copy(); copy.apply(move);
            if (!copy.inCheck(side)) result.add(move);
        }
        return result;
    }

    /** Applies standard algebraic notation generated by this client, or UCI as a recovery format. */
    @Override public boolean move(String wireMove) {
        if (wireMove == null || isFinished()) return false;
        String requested = normalise(wireMove);
        List<Move> legal = legalMoveObjects();
        Move selected = null;
        for (Move move : legal) {
            String notation = normalise(san(move));
            if (requested.equals(notation)) { selected = move; break; }
            String coordinate = square(move.fromRow, move.fromColumn) + square(move.toRow, move.toColumn)
                    + (move.promotion == 0 ? "" : String.valueOf(Character.toLowerCase(move.promotion)));
            if (requested.equals(coordinate)) { selected = move; break; }
        }
        if (selected == null) return false;
        apply(selected);
        updateStatus();
        return true;
    }

    /** Used by the board GUI to choose source/destination and a promotion piece. */
    public String move(int fromRow, int fromColumn, int toRow, int toColumn, char promotion) {
        if (isFinished()) return null;
        for (Move move : legalMoveObjects()) if (move.fromRow == fromRow && move.fromColumn == fromColumn
                && move.toRow == toRow && move.toColumn == toColumn) {
            if (move.promotion != 0 && Character.toUpperCase(promotion) != move.promotion) continue;
            String notation = san(move); apply(move); updateStatus(); return notation;
        }
        return null;
    }

    public boolean requiresPromotion(int fromRow, int fromColumn, int toRow, int toColumn) {
        char piece = board[fromRow][fromColumn];
        return Character.toUpperCase(piece) == 'P' && (toRow == 0 || toRow == 7) && !legalMoveObjects().isEmpty();
    }

    /** Returns the exact SAN token that this client will send for a board click. */
    public String notationFor(int fromRow, int fromColumn, int toRow, int toColumn, char promotion) {
        for (Move move : legalMoveObjects()) if (move.fromRow == fromRow && move.fromColumn == fromColumn
                && move.toRow == toRow && move.toColumn == toColumn
                && (move.promotion == 0 || Character.toUpperCase(promotion) == move.promotion)) return san(move);
        return null;
    }

    @Override public String chooseRobotMove(int strength, Random random) {
        List<Move> moves = legalMoveObjects(); if (moves.isEmpty()) return null;
        if (strength <= 2) return san(moves.get(random.nextInt(moves.size())));
        int robot = turn, best = Integer.MIN_VALUE; Move selected = moves.get(0);
        for (Move move : moves) {
            ChessGameState child = copy(); child.apply(move); child.updateStatus();
            int score = child.score(robot);
            if (strength >= 6 && !child.isFinished()) {
                int reply = Integer.MAX_VALUE;
                for (Move opposing : child.legalMoveObjects()) { ChessGameState after = child.copy(); after.apply(opposing); after.updateStatus(); reply = Math.min(reply, after.score(robot)); }
                if (reply != Integer.MAX_VALUE) score = reply;
            }
            if (score > best || score == best && random.nextBoolean()) { best = score; selected = move; }
        }
        return san(selected);
    }

    private List<Move> pseudoMoves(int side) {
        List<Move> moves = new ArrayList<Move>();
        for (int row = 0; row < 8; row++) for (int col = 0; col < 8; col++) {
            char piece = board[row][col]; if (piece == ' ' || sideOf(piece) != side) continue;
            switch (Character.toUpperCase(piece)) {
                case 'P': pawnMoves(moves, row, col, side); break;
                case 'N': jumpMoves(moves, row, col, side, new int[][] {{-2,-1},{-2,1},{-1,-2},{-1,2},{1,-2},{1,2},{2,-1},{2,1}}); break;
                case 'B': rayMoves(moves, row, col, side, new int[][] {{-1,-1},{-1,1},{1,-1},{1,1}}); break;
                case 'R': rayMoves(moves, row, col, side, new int[][] {{-1,0},{1,0},{0,-1},{0,1}}); break;
                case 'Q': rayMoves(moves, row, col, side, new int[][] {{-1,-1},{-1,1},{1,-1},{1,1},{-1,0},{1,0},{0,-1},{0,1}}); break;
                case 'K': kingMoves(moves, row, col, side); break;
                default: break;
            }
        }
        return moves;
    }

    private void pawnMoves(List<Move> moves, int row, int col, int side) {
        int direction = side == 0 ? -1 : 1, start = side == 0 ? 6 : 1, promotion = side == 0 ? 0 : 7;
        int next = row + direction;
        if (inside(next, col) && board[next][col] == ' ') {
            addPawnMove(moves, row, col, next, col, promotion);
            if (row == start && board[row + direction * 2][col] == ' ') moves.add(new Move(row, col, row + direction * 2, col));
        }
        for (int delta : new int[] {-1, 1}) {
            int target = col + delta; if (!inside(next, target)) continue;
            if (board[next][target] != ' ' && sideOf(board[next][target]) != side) addPawnMove(moves, row, col, next, target, promotion);
            if (row == (side == 0 ? 3 : 4) && target == enPassantColumn && board[row][target] == (side == 0 ? 'p' : 'P')) {
                Move enPassant = new Move(row, col, next, target); enPassant.enPassant = true; moves.add(enPassant);
            }
        }
    }
    private void addPawnMove(List<Move> moves, int fromRow, int fromCol, int toRow, int toCol, int promotionRow) {
        if (toRow != promotionRow) { moves.add(new Move(fromRow, fromCol, toRow, toCol)); return; }
        for (char promotion : new char[] {'Q','R','B','N'}) moves.add(new Move(fromRow, fromCol, toRow, toCol, promotion));
    }
    private void jumpMoves(List<Move> moves, int row, int col, int side, int[][] offsets) {
        for (int[] offset : offsets) addIfOpen(moves, row, col, row + offset[0], col + offset[1], side);
    }
    private void rayMoves(List<Move> moves, int row, int col, int side, int[][] directions) {
        for (int[] direction : directions) for (int r = row + direction[0], c = col + direction[1]; inside(r,c); r += direction[0], c += direction[1]) {
            if (board[r][c] == ' ') { moves.add(new Move(row,col,r,c)); continue; }
            if (sideOf(board[r][c]) != side) moves.add(new Move(row,col,r,c)); break;
        }
    }
    private void kingMoves(List<Move> moves, int row, int col, int side) {
        for (int dr = -1; dr <= 1; dr++) for (int dc = -1; dc <= 1; dc++) if (dr != 0 || dc != 0) addIfOpen(moves,row,col,row+dr,col+dc,side);
        if (side == 0 && row == 7 && col == 4 && !inCheck(0)) {
            if (whiteKingSide && board[7][5] == ' ' && board[7][6] == ' ' && board[7][7] == 'R' && !attacked(7,5,1) && !attacked(7,6,1)) moves.add(new Move(7,4,7,6));
            if (whiteQueenSide && board[7][1] == ' ' && board[7][2] == ' ' && board[7][3] == ' ' && board[7][0] == 'R' && !attacked(7,3,1) && !attacked(7,2,1)) moves.add(new Move(7,4,7,2));
        } else if (side == 1 && row == 0 && col == 4 && !inCheck(1)) {
            if (blackKingSide && board[0][5] == ' ' && board[0][6] == ' ' && board[0][7] == 'r' && !attacked(0,5,0) && !attacked(0,6,0)) moves.add(new Move(0,4,0,6));
            if (blackQueenSide && board[0][1] == ' ' && board[0][2] == ' ' && board[0][3] == ' ' && board[0][0] == 'r' && !attacked(0,3,0) && !attacked(0,2,0)) moves.add(new Move(0,4,0,2));
        }
    }
    private void addIfOpen(List<Move> moves, int fromRow, int fromCol, int row, int col, int side) {
        if (inside(row,col) && (board[row][col] == ' ' || sideOf(board[row][col]) != side)) moves.add(new Move(fromRow,fromCol,row,col));
    }

    private boolean inCheck(int side) { for (int row = 0; row < 8; row++) for (int col = 0; col < 8; col++) if (board[row][col] == (side == 0 ? 'K' : 'k')) return attacked(row,col,1-side); return true; }
    private boolean attacked(int row, int col, int by) {
        int pawnRow = row + (by == 0 ? 1 : -1); for (int dc : new int[] {-1,1}) if (inside(pawnRow,col+dc) && board[pawnRow][col+dc] == (by == 0 ? 'P' : 'p')) return true;
        for (int[] d : new int[][] {{-2,-1},{-2,1},{-1,-2},{-1,2},{1,-2},{1,2},{2,-1},{2,1}}) if (inside(row+d[0],col+d[1]) && board[row+d[0]][col+d[1]] == (by == 0 ? 'N' : 'n')) return true;
        for (int[] d : new int[][] {{-1,-1},{-1,1},{1,-1},{1,1}}) if (rayAttack(row,col,d,by,'B','Q')) return true;
        for (int[] d : new int[][] {{-1,0},{1,0},{0,-1},{0,1}}) if (rayAttack(row,col,d,by,'R','Q')) return true;
        for (int dr=-1; dr<=1; dr++) for (int dc=-1; dc<=1; dc++) if ((dr!=0||dc!=0) && inside(row+dr,col+dc) && board[row+dr][col+dc] == (by==0?'K':'k')) return true;
        return false;
    }
    private boolean rayAttack(int row, int col, int[] d, int by, char one, char two) { for (row += d[0], col += d[1]; inside(row,col); row += d[0], col += d[1]) { char p=board[row][col]; if(p==' ')continue; return sideOf(p)==by && (Character.toUpperCase(p)==one || Character.toUpperCase(p)==two); } return false; }

    private String san(Move move) {
        char piece = board[move.fromRow][move.fromColumn];
        if (Character.toUpperCase(piece) == 'K' && Math.abs(move.toColumn - move.fromColumn) == 2) return move.toColumn > move.fromColumn ? "O-O" : "O-O-O";
        boolean capture = board[move.toRow][move.toColumn] != ' ' || move.enPassant;
        StringBuilder result = new StringBuilder();
        char type = Character.toUpperCase(piece);
        if (type != 'P') {
            result.append(type);
            boolean sameFile = false, sameRank = false, conflict = false;
            for (Move other : legalMoveObjects()) if (other.fromRow != move.fromRow || other.fromColumn != move.fromColumn) {
                if (other.toRow == move.toRow && other.toColumn == move.toColumn && board[other.fromRow][other.fromColumn] == piece) { conflict = true; sameFile |= other.fromColumn == move.fromColumn; sameRank |= other.fromRow == move.fromRow; }
            }
            if (conflict) { if (!sameFile) result.append((char)('a'+move.fromColumn)); else if (!sameRank) result.append(8-move.fromRow); else result.append(square(move.fromRow,move.fromColumn)); }
        } else if (capture) result.append((char) ('a' + move.fromColumn));
        if (capture) result.append('x'); result.append(square(move.toRow,move.toColumn));
        if (move.promotion != 0) result.append('=').append(move.promotion);
        ChessGameState copy = copy(); copy.apply(move);
        if (copy.inCheck(copy.turn)) result.append(copy.legalMoveObjects().isEmpty() ? '#' : '+');
        return result.toString();
    }

    private void apply(Move move) {
        char piece = board[move.fromRow][move.fromColumn];
        char captured = board[move.toRow][move.toColumn];
        if (move.enPassant) { captured = board[move.fromRow][move.toColumn]; board[move.fromRow][move.toColumn] = ' '; }
        board[move.fromRow][move.fromColumn] = ' '; board[move.toRow][move.toColumn] = piece;
        if (move.promotion != 0) board[move.toRow][move.toColumn] = turn == 0 ? move.promotion : Character.toLowerCase(move.promotion);
        if (Character.toUpperCase(piece) == 'K') {
            if (turn == 0) { whiteKingSide = false; whiteQueenSide = false; } else { blackKingSide = false; blackQueenSide = false; }
            if (Math.abs(move.toColumn - move.fromColumn) == 2) { int rookFrom = move.toColumn > move.fromColumn ? 7 : 0, rookTo = move.toColumn > move.fromColumn ? 5 : 3; board[move.toRow][rookTo] = board[move.toRow][rookFrom]; board[move.toRow][rookFrom] = ' '; }
        }
        if (piece == 'R' && move.fromRow == 7) { if (move.fromColumn == 0) whiteQueenSide = false; if (move.fromColumn == 7) whiteKingSide = false; }
        if (piece == 'r' && move.fromRow == 0) { if (move.fromColumn == 0) blackQueenSide = false; if (move.fromColumn == 7) blackKingSide = false; }
        if (captured == 'R' && move.toRow == 7) { if (move.toColumn == 0) whiteQueenSide = false; if (move.toColumn == 7) whiteKingSide = false; }
        if (captured == 'r' && move.toRow == 0) { if (move.toColumn == 0) blackQueenSide = false; if (move.toColumn == 7) blackKingSide = false; }
        enPassantColumn = Character.toUpperCase(piece) == 'P' && Math.abs(move.toRow - move.fromRow) == 2 ? move.fromColumn : -1;
        lastMove = move; turn = 1 - turn;
    }
    private void updateStatus() { List<Move> next = legalMoveObjects(); if (next.isEmpty()) status = inCheck(turn) ? "Checkmate — " + (turn == 0 ? "Black" : "White") + " wins" : "Stalemate"; else status = (turn == 0 ? "White" : "Black") + (inCheck(turn) ? " in check" : " to move"); }
    private int score(int side) { int score=0; for(int r=0;r<8;r++)for(int c=0;c<8;c++){char p=board[r][c]; int v=Character.toUpperCase(p)=='P'?100:Character.toUpperCase(p)=='N'||Character.toUpperCase(p)=='B'?320:Character.toUpperCase(p)=='R'?500:Character.toUpperCase(p)=='Q'?900:Character.toUpperCase(p)=='K'?20000:0; if(p!=' ')score+=sideOf(p)==side?v:-v;} return score+(isFinished()&&status.startsWith("Checkmate")?(status.contains(side==0?"White":"Black")?100000:-100000):0); }
    private ChessGameState copy() { ChessGameState result=new ChessGameState(); for(int r=0;r<8;r++)System.arraycopy(board[r],0,result.board[r],0,8); result.turn=turn;result.whiteKingSide=whiteKingSide;result.whiteQueenSide=whiteQueenSide;result.blackKingSide=blackKingSide;result.blackQueenSide=blackQueenSide;result.enPassantColumn=enPassantColumn;result.status=status;result.lastMove=lastMove;return result; }
    private static String normalise(String text) { return text.trim().replace("0-0-0","O-O-O").replace("0-0","O-O").replace(" e.p.","").replace("ep","").replaceAll("[+#!?]$","").replace(" ","").toLowerCase(Locale.ROOT); }
    private static int sideOf(char piece) { return Character.isUpperCase(piece) ? 0 : Character.isLowerCase(piece) ? 1 : -1; }
    private static boolean inside(int row,int col) { return row>=0&&row<8&&col>=0&&col<8; }
    private static String square(int row,int col) { return ""+(char)('a'+col)+(char)('8'-row); }

    public static final class Move {
        public final int fromRow, fromColumn, toRow, toColumn; public final char promotion; boolean enPassant;
        Move(int fr,int fc,int tr,int tc) { this(fr,fc,tr,tc,(char)0); }
        Move(int fr,int fc,int tr,int tc,char promotion) { fromRow=fr;fromColumn=fc;toRow=tr;toColumn=tc;this.promotion=promotion; }
    }
}
